### ISSUE TITLE
Add Luovatone's "Tone" brushes to Repository

### ISSUE THREAD

**Issue by AtsusaKaneytza** [Jehan/mypaint-brushes#1]
Brushpack mentioned here:
https://github.com/mypaint/mypaint/issues/842#issuecomment-338114389

MyPaint Community comment:
https://community.mypaint.org/t/cant-find-luovatones-brushset-v2-tone-help/758

Luovatone's Brush Package:
[tone_v2.zip](https://github.com/Jehan/mypaint-brushes/files/1424214/tone_v2.zip)

**Comment by Jehan** [comment]
Hello!

Thanks but right now the purpose of this repository is to be included upstream at MyPaint organization.  See: https://github.com/mypaint/mypaint/pull/538

So I will not be the one to accept new brushes. But once this repository will be owned by MyPaint upstream, you will be able to propose again.
I leave your 3 reports opened though, because maybe we can just move the whole repo later (ownership change) and then these reports would be moved together. :-)

**Comment by AtsusaKaneytza** [comment]
alright then!

**Comment by Jehan** [comment]
Hi!

The `mypaint-brush` package is now officially at: https://github.com/mypaint/mypaint-brushes/

You are welcome to make again your request for brush adding there, if you still want.

We still needed to clarify a point about the official brush package licensing policy (see https://github.com/mypaint/mypaint-brushes/commit/5adf08db45aa18a2ceeac1d5084e8e5de57caea9). Basically all brush in this package must be released in the public domain (CC0 1.0). I had a look in the zip of these brushes and there does not seem to be any licensing information available.

If you are the author, please be aware that requesting your brushes to be in this package means for releasing them as public domain. If you are not the author, please beforehand requesting inclusion, ensure they are ok with it by either finding a source where they already said it was CC0 or by contacting them.

I will now close this report as any further discussion will have to be done on a new report on the new [official repo](https://github.com/mypaint/mypaint-brushes/).
