### ISSUE TITLE
mypaint-brushes install to different directory than mypaint expects

### ISSUE THREAD

**Issue by jbicha** [Jehan/mypaint-brushes#6]
Ubuntu 18.04 Beta

mypaint-brushes 1.3.0 installs to `/usr/share/mypaint-data/1.0/brushes/`

However, myapint 1.2.1 looks for brushes in `/usr/share/mypaint/brushes/`

Please have these directories match.

**Comment by Jehan** [comment]
One of the point of this separate package is to version the data.
Basically data evolve and brushes made for libmypaint 2 are not compatible with brushes made for libmypaint 1. This is not a theoretical assumption. There are actual evolutions already of the brushes, which got new properties, but also some of the brush properties changed (there are even some crashes if libmypaint 1 tries to load some of libmypaint 2 currently, though this is a bug which should be fixed eventually). Hence the "1.0" in the path.

Another point is to share the data between packages. MyPaint currently embeds all its brushes in its repository and install them. If all software were to do this, we'd have every software out there (MyPaint, GIMP, etc.) who would duplicate this data, which is not good. This is why it is in its own namespace "mypaint-data" and not "mypaint".

Now currently MyPaint has not added mypaint-brushes as a dependency yet. So that's even more reason to not have the directories match. Not until they remove the brushes from their repository. If we were to try and match what is in MyPaint, a mypaint-brushes package would clash with a MyPaint package (therefore, for instance, it would be impossible to install both GIMP and MyPaint!). Instead, we are just waiting for the MyPaint project to make mypaint-brushes a dependency. When they will do so, the path `/usr/share/mypaint/brushes/` should just disappear.

A report is open at MyPaint's for this: https://github.com/mypaint/mypaint/pull/538
Note that I also expect them to take ownership of this repository. I am only a temporary owner. Things may change a bit then, and if MyPaint main developers decide for slightly different folders, we will follow their decision (I will optionally discuss it of course). But for the time being, until this day comes, this cannot change.

**Comment by Jehan** [comment]
Not sure why I left this opened since I answered your worry already.

Anyway since it's still opened, let it be known that this package has finally be moved at MyPaint project, making this other repo the new place to report issues and make merge requests: https://github.com/mypaint/mypaint-brushes
